org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError

android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Keep the Gradle daemon alive in memory across builds
org.gradle.daemon=true

# Allow Gradle to compile independent modules in parallel
org.gradle.parallel=true

# Enable task output caching
org.gradle.caching=true

# Expand JVM heap memory allocated to Gradle tasks
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC